---
# This playbook deploys the whole application stack

- hosts: all
  tasks:
    - action: shell whoami
      register: whoami

    # Keys and repositories
    # So you only need to update once
    - name: install docker key
      sudo: yes
      apt_key: url=https://get.docker.io/gpg state=present

    - name: add repository
      sudo: yes
      command: sh -c "echo deb http://get.docker.io/ubuntu docker main > /etc/apt/sources.list.d/docker.list"

    # Update
    - name: update apt cache
      apt: update_cache=yes cache_valid_time=3600
      sudo: yes

    - name: upgrade the distro
      apt: upgrade=yes
      sudo: yes

    # Common packages
    - name: install packages
      apt: pkg={{ item }} state=latest install_recommends=no
      sudo: yes
      with_items:
        - build-essential
        - vim
        - runit
        - git
        - openssh-server
        - tmux
        - zsh
        - fail2ban

    # Install docker
    - name: install docker
      sudo: yes
      apt: pkg=lxc-docker state=latest

    - name: ensure docker is running
      sudo: yes
      service: name=docker state=started enabled=true

    # Install redis container
    - name: docker pull nxqd/redis
      tags: docker
      sudo: yes
      command: docker pull nxqd/redis

    - name: docker run redis container
      tags: docker
      sudo: yes
      command: docker run -dt --name redis nxqd/redis

    # Check fail2ban
    - name: ensure fail2ban is running
      tags: security
      sudo: yes
      action: service name=fail2ban state=restarted enabled=yes

    # Forbid ssh root login
    - name: forbid SSH root login
      tags: security
      sudo: yes
      lineinfile: destfile=/etc/ssh/sshd_config regexp="^PermitRootLogin" line="PermitRootLogin no" state=present
      notify:
        - restart ssh

    # Firewall
    - name: reset firewall
      sudo: yes
      action: shell ufw --force reset

    - name: allow firewall authorized ports
      sudo: yes
      tags: security
      action: shell ufw allow {{ item }}
      with_items:
        - 22
        - 80

    - name: reset firewall
      sudo: yes
      action: shell ufw --force enable

    # Clean up
    #- name: clean up
    #  sudo: yes
    #  apt: pkg=clean

  handlers:
    - name: restart ssh
      tags: security
      action: service name=ssh state=restarted enabled=yes